[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# All SSR pages
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
