[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"

# 1. Redirect all API requests to Nitro serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# 2. Redirect ALL other requests to the serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
