[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"

# 1. Route all /api requests to SSR function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# 2. Route all other pages to SSR function (SSR fallback)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
