# basic Decap config - edit repo & branch to match yours
backend:
  name: github
  repo: wissam333/3lioo
  branch: master
  auth_type: implicit
  app_id: Ov23li8YCwCVhHzQOghp

media_folder: "static/uploads"
public_folder: "/uploads"


media_folder: "static/uploads"   # where images/attachments are stored in repo
public_folder: "/uploads"        # how they're referenced on the site

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
